{% set name = "pyfao56" %}
{% set version = "1.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfao56-{{ version }}.tar.gz
  sha256: 11a0d20ea03cc2021f5a3dbdeef3f0d9a31d7e3f67e95695665dd15df525f872

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7
    - requests
    - urllib3

test:
  imports:
    - pyfao56
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/kthorp/pyfao56
  summary: FAO-56 in Python
  dev_url: http://github.com/kthorp/pyfao56
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kthorp
