{% set name = "pyfao56" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfao56-{{ version }}.tar.gz
  sha256: 2a536cd75e102bb0d4c655392a30fba91b7cac1c6372c2af2a5b3beb539cff0e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests
    - urllib3

test:
  imports:
    - pyfao56
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/kthorp/pyfao56
  summary: FAO-56 Evapotranspiration in Python
  dev_url: http://github.com/kthorp/pyfao56
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kthorp
