{% set name = "pyfao56" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfao56-{{ version }}.tar.gz
  sha256: 434a0405eb66138e9a2fb50297a98d03196897b756feb9a434a466f5627479e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib
    - numpy
    - pandas
    - python >=3.7
    - requests
    - urllib3

test:
  imports:
    - pyfao56
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/kthorp/pyfao56
  summary: FAO-56 in Python
  dev_url: http://github.com/kthorp/pyfao56
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kthorp
