{% set name = "pyfao56" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfao56-{{ version }}.tar.gz
  sha256: 8ff99adfb1768d84ae4f4df7a2c128e5518f994502c7569983bc874b6b3769c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests
    - urllib3

test:
  imports:
    - pyfao56
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/kthorp/pyfao56
  summary: FAO-56 Evapotranspiration in Python
  dev_url: http://github.com/kthorp/pyfao56
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kthorp
